// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa7kZznnyb7S4MzKAkwVs2c7HwHiVcAUE',
    appId: '1:705533795103:web:855bc52f7513ee92af2e2a',
    messagingSenderId: '705533795103',
    projectId: 'evently-56a15',
    authDomain: 'evently-56a15.firebaseapp.com',
    storageBucket: 'evently-56a15.firebasestorage.app',
    measurementId: 'G-S18JETQBBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcaiQxaXZBzCcK5UfizyipWFSTK51HRrs',
    appId: '1:705533795103:android:06968f2e00a98cedaf2e2a',
    messagingSenderId: '705533795103',
    projectId: 'evently-56a15',
    storageBucket: 'evently-56a15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9u6mXAc-KWrFJ6ZnApiWVPjN9djPX_9M',
    appId: '1:705533795103:ios:8c8eb3d969502bd6af2e2a',
    messagingSenderId: '705533795103',
    projectId: 'evently-56a15',
    storageBucket: 'evently-56a15.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9u6mXAc-KWrFJ6ZnApiWVPjN9djPX_9M',
    appId: '1:705533795103:ios:8c8eb3d969502bd6af2e2a',
    messagingSenderId: '705533795103',
    projectId: 'evently-56a15',
    storageBucket: 'evently-56a15.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa7kZznnyb7S4MzKAkwVs2c7HwHiVcAUE',
    appId: '1:705533795103:web:fe81f21c928ebb63af2e2a',
    messagingSenderId: '705533795103',
    projectId: 'evently-56a15',
    authDomain: 'evently-56a15.firebaseapp.com',
    storageBucket: 'evently-56a15.firebasestorage.app',
    measurementId: 'G-D7ZBH4V5TR',
  );

}